# Generated by Django 2.1.1 on 2018-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='edad',
            field=models.CharField(default='NULL', max_length=2),
        ),
    ]
