# Generated by Django 2.1.1 on 2018-09-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_alumnos', '0002_alumnos_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnos',
            name='edad',
        ),
    ]
